export const TRADE_REQUEST_POSTS = "TRADE_REQUEST_POSTS";
export const TRADE_RECEIVE_COMMODITY = "TRADE_RECEIVE_COMMODITY";
export const TRADE_RECEIVE_STRATEGY = "TRADE_RECEIVE_STRATEGY";
export const TRADE_BOOKING_END = "TRADE_BOOKING_END";
export const REQUEST_START = "REQUEST_START";